# Generated by Django 3.1.3 on 2022-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='轮播图片')),
                ('link', models.URLField(verbose_name='广告链接')),
                ('name', models.CharField(max_length=200, verbose_name='广告标题')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '轮播广告',
                'verbose_name_plural': '轮播广告',
                'db_table': 'banner',
            },
        ),
    ]
